name: CI

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

jobs:
    build-development:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest

                node-version:
                    - 12.x
                    # - 14.x
                    - 16.x

        env:
            NODE_ENV: development

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - run: npm ci

            - run: NODE_ENV=development npx webpack
            # - run: npm test

    build-production:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest

                node-version:
                    - 12.x
                    # - 14.x
                    - 16.x

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - run: npm ci

            - run: npm run build
            # - run: npm test

    build-release:
        needs:
            - build-development
            - build-production

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: "npm"

            - run: npm ci

            - run: npm run build

            - name: Build ZIP archive
              run: |
                  rm -rf ./build
                  mkdir -p ./build
                  (cd ./public/extension && zip ../../build/turbulence.zip -r ./)
                  unzip -l ./build/turbulence.zip

            - uses: actions/upload-artifact@v2
              with:
                  name: turbulence.zip
                  path: build/turbulence.zip
                  retention-days: 7
